# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: api_solides/api_v_1_0_18.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
    no-ambiguous-paths: off
referenceDocs:
  showConsole: false # Enable the API Console (the Try it functionality).
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
